# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = jcqtOpenGL
DESTDIR = ../x64/Debug
CONFIG += debug
DEFINES += JCQTOPENGL_LIB
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(jcqtOpenGL.pri)
