# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

QT += core opengl gui concurrent
TEMPLATE = lib
TARGET = jcqtOpenGL
DESTDIR = ../x64/Debug
CONFIG += debug_and_release
DEFINES += JCQTOPENGL_LIB
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
RESOURCES += ./assets.qrc
include(jcqtOpenGL.pri)
