# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = jcqt3DTest
DESTDIR = ../x64/Debug
QT += gui opengl
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
RESOURCES += ./assets.qrc
include(jcqt3DTest.pri)
